#!/usr/bin/env python3
"""Fetch verified metadata for the paper's citations from the arXiv API.

The project rule is that every citation is checked against ground truth before
shipping, so the bibliography is fetched rather than transcribed. Author lists
and titles come from arXiv; venue fields are deliberately left out and are a
camera-ready task (an arXiv record does not tell us where a paper was published).

    python scripts/fetch_bib.py    ->  paper/refs.bib
"""
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "paper" / "refs.bib"

# citation key -> arXiv id, as cited in Section 2 of the paper
CITES = {
    "yao2024taubench": "2406.12045",
    "cuadron2025saber": "2512.07850",
    "gupta2026reliabilitybench": "2601.06112",
    "rabanser2026science": "2602.16666",
    "malay2026enterpriseops": "2603.13594",
    "khanal2026beyond": "2603.29231",
    "li2026clawsbench": "2604.05172",
    "yeke2026yesman": "2605.20544",
    "hu2026saber": "2606.01317",
    "ojewale2026abstention": "2606.02965",
    "liu2026agentabstain": "2607.10059",
}

NS = {"a": "http://www.w3.org/2005/Atom"}

# arXiv titles carry raw unicode that pdflatex cannot typeset. Map the
# characters that actually occur to their LaTeX equivalents rather than
# stripping them, so the rendered title still matches the fetched record.
# The keys are deliberately the literal characters that occur in arXiv titles.
# Replacing them with ASCII look-alikes would stop the mapping from matching.
UNICODE_FIX = {
    "τ": r"\tau",     # tau-bench, already inside $...$ in the arXiv title
    "–": "--",
    "—": "---",
    "‘": "`", "’": "'",
    "“": "``", "”": "''",
}


def to_latex(text):
    for bad, good in UNICODE_FIX.items():
        text = text.replace(bad, good)
    non_ascii = {c for c in text if ord(c) > 127}
    if non_ascii:
        sys.exit(f"unmapped non-ASCII {non_ascii!r} in: {text[:60]}")
    return text


# plainnat lowercases a title past its first word, which turns SABER into
# Saber, LLM into llm, and EnterpriseOps-Gym into Enterpriseops-gym. Any token
# carrying a capital past its first letter is a proper noun or an acronym, so
# brace it. The rule is structural rather than a list of names, so a citation
# added later is protected without anyone remembering to add it here.
WORD = re.compile(r"[A-Za-z0-9@'-]+")


def protect_caps(title):
    def brace(m):
        w = m.group(0)
        return "{" + w + "}" if len(w) > 1 and any(c.isupper() for c in w[1:]) else w

    # Math segments are already typeset; leave them exactly as fetched.
    parts = re.split(r"(\$[^$]*\$)", title)
    return "".join(p if p.startswith("$") else WORD.sub(brace, p) for p in parts)


def fix_name(name):
    """Keep BibTeX from misreading a fetched author name.

    A hyphenated given name whose second half is lowercase, such as
    Han-chung, parses as first=Han von=chung last=Lee: it prints as "Han chung
    Lee" and sorts under "chung". Bracing the token keeps it whole. A bare
    single-letter initial also gets its period, which arXiv's metadata omits.
    """
    parts = []
    for tok in name.split():
        if "-" in tok and re.search(r"-[a-z]", tok):
            tok = "{" + tok + "}"
        elif len(tok) == 1 and tok.isalpha() and tok.isupper():
            tok = tok + "."
        parts.append(tok)
    return " ".join(parts)


def fetch():
    url = ("https://export.arxiv.org/api/query?id_list="
           + ",".join(CITES.values()) + f"&max_results={len(CITES) * 2}")
    root = ET.fromstring(urllib.request.urlopen(url, timeout=60).read())
    by_id = {}
    for e in root.findall("a:entry", NS):
        raw = e.find("a:id", NS).text.rsplit("/", 1)[-1]
        base = raw.split("v")[0]
        by_id[base] = {
            "version": raw,
            "title": to_latex(" ".join(e.find("a:title", NS).text.split())),
            "authors": [to_latex(a.find("a:name", NS).text)
                        for a in e.findall("a:author", NS)],
            "year": e.find("a:published", NS).text[:4],
            "primary": (e.find("{http://arxiv.org/schemas/atom}primary_category")
                        .get("term")),
        }
    return by_id


def main():
    by_id = fetch()
    missing = [k for k, aid in CITES.items() if aid not in by_id]
    if missing:
        sys.exit(f"arXiv returned no record for: {missing}")

    lines = ["% Generated by scripts/fetch_bib.py from the arXiv API.",
             "% Titles and author lists are fetched, not transcribed.",
             "% TODO camera-ready: add published venue fields where applicable.",
             ""]
    for key, aid in CITES.items():
        m = by_id[aid]
        authors = " and ".join(fix_name(a) for a in m["authors"])
        lines += [
            f"@misc{{{key},",
            f"  title         = {{{protect_caps(m['title'])}}},",
            f"  author        = {{{authors}}},",
            f"  year          = {{{m['year']}}},",
            f"  eprint        = {{{aid}}},",
            "  archivePrefix = {arXiv},",
            f"  primaryClass  = {{{m['primary']}}},",
            # plainnat prints neither eprint nor archivePrefix, so without
            # these two the rendered entry is author, title, year and nothing
            # a reader could use to find the paper.
            f"  howpublished  = {{arXiv:{aid} [{m['primary']}]}},",
            f"  url           = {{https://arxiv.org/abs/{aid}}}",
            "}",
            "",
        ]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO)}: {len(CITES)} entries verified")
    for key, aid in CITES.items():
        m = by_id[aid]
        print(f"  {key:28s} {aid} ({m['version']}) {len(m['authors']):2d}a  "
              f"{m['title'][:52]}")


if __name__ == "__main__":
    main()
